spring.application.name=renthub-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/renthub_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect